### PR TITLE
CONTRIB: Apply the environment on the first chef-client run; otherwise, the envir...

### PR DESCRIPTION
**Pull request by nabeelio**
Use the -E [environment] on the first run of the chef-client, otherwise, the environment is not applied to the node, and the provisioning can fail, depending on what the settings for the environment are.

### CODE REVIEW

**Comment by lopaka** [comment]
Hello Nabeel,

We appreciate your contribution to the RightScale cookbooks.  Before we can proceed with the process of reviewing and merging your pull request, please follow step one on our [Contribute to RightScale Cookbooks](http://support.rightscale.com/12-Guides/Chef_Cookbooks_Developer_Guide/04-Developer/ServerTemplate_Development/08-Common_Development_Tasks/03-Contribute_to_RightScale_Cookbooks) site and sign the [RightScale Contributors Agreement](https://rightscale.echosign.com/public/hostedForm?formid=3SMKS95X3F5G3S).

Thank you.

**Comment by nabeelio** [comment]
No problem, done

**Comment by lopaka** [comment]
Made comment about the `-E` flag not needed on line [74](https://github.com/nshahzad/rightscale_cookbooks/commit/08b633e26b6a2aec1593949cd41a17606380aa40#cookbooks-chef-recipes-install_client-rb-P5).

As a result, I will be closing this pull request.  Please comment and reopen if you feel this should still be addressed.

Thanks,
Lopaka

**Comment by lopaka** [comment]
Reopened to investigate claims of chef-environment not applied at first start.

**Comment by autrejacoupa** [comment]
We need -E <environment> option. Cannot get RS "Chef Client Beta (v13.3)" template to work with chef environment.

**Comment by lopaka** [comment]
Currently being worked on.

**Comment by lopaka** [comment]
Commits have been cherry picked to our development repository and worked on to follow our coding standards and logic.  As a result, this code review will be closed.  Once we push the code to public, you will be able to view your commit.  Thanks for your contribution.

**Pull request closed without merging**
